name: Update Documentation
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**/*.md'
      - 'docs/images/**'  # Add this to track image changes
  pull_request:
    paths:
      - 'docs/**/*.md'
      - 'docs/images/**'  # Add this to track image changes

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify markdown files
        run: |
          echo "Verifying markdown files..."
          find docs -name "*.md" -type f -exec echo "Checking {}" \;
          
      - name: Verify image paths
        run: |
          echo "Checking image paths..."
          find docs -name "*.md" -type f -exec grep -l "!\[.*\](.*)" {} \;
          
      - name: Process images
        run: |
          echo "Processing documentation images..."
          if [ -d "docs/images" ]; then
            echo "Found images directory"
            ls -la docs/images/
          fi

      - name: Check relative paths
        run: |
          echo "Validating relative paths in markdown files..."
          # Add specific path validation if needed